development:
  adapter: <%= ENV['ADAPTER'] %>
  database: <%= ENV['DB_DEV'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
               
test:
  adapter: <%= ENV['ADAPTER'] %>
  database: <%= ENV['DB_TEST'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
                                
